# Generated by Django 3.2.7 on 2021-10-17 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=45)),
                ('nombres', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField(auto_now_add=True)),
                ('aprobado', models.BooleanField(null=True)),
                ('visitas', models.IntegerField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individuos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
