# Generated by Django 3.2.9 on 2021-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_individuo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuo',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='individuo',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='individuo',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
