# Generated by Django 3.2.9 on 2021-11-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20211118_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('abierto', models.BooleanField(default=False)),
                ('entidad', models.CharField(max_length=45)),
                ('monto', models.IntegerField(default=0)),
                ('comentarios', models.CharField(max_length=45)),
                ('aprobado', models.BooleanField(default=False)),
                ('visitas', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
