# Generated by Django 3.2.9 on 2021-11-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('aprobado', models.BooleanField(default=False)),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individuos', to='app.individuo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='app.partido')),
            ],
        ),
    ]
